name: Validate Docker Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate-docker-build:
    name: Build Docker Image (no push)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/docker/Dockerfile
          push: false
